# Actividad Modulo 8
## NumPy: Operaciones con arreglos y matrices
### Ejercicios: 
1. Escribe un programa que mediante indexación en NumPy sea capaz de invertir un arreglo (donde el primer elemento se convierte en el último)

In [1]:
import numpy as np

In [3]:
arreglo = np.arange(12,21)
arreglo

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arreglo[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

2. Escribe un programa con NumPy para convertir valores de grados Fahrenheit a grados centigrados. Los valores se almacenan en un arreglo de salida.

In [14]:
f = np.array([0,12,45.21,34,99.91,32])
f

array([ 0.  , 12.  , 45.21, 34.  , 99.91, 32.  ])

In [28]:
c = np.round((5*(f-32))/9.,2)
c

array([-17.78, -11.11,   7.34,   1.11,  37.73,   0.  ])

3. Escribe un programa con NumPy para encontrar la unión de dos arreglos. La unión debe devolver un arreglo ordenado de valores que están en cualquiera de los dos arreglos de entrada (sin repetición).

In [34]:
array1=np.arange(0,30,10)
array1

array([ 0, 10, 20])

In [36]:
array2=np.array([20,10,30])
array2

array([20, 10, 30])

In [45]:
array = np.concatenate((array1,array2))

In [52]:
array = np.sort(array)

array([ 0, 10, 10, 20, 20, 30])

In [54]:
np.array(set(np.concatenate((array1,array2))))

array({0, 10, 20, 30}, dtype=object)

                                                                                                           Tao Izzo Elvira 